export const thaiFonts = [
  { name: "Prompt", value: "'Prompt', sans-serif" },
  { name: "Kanit", value: "'Kanit', sans-serif" },
  { name: "Sarabun", value: "'Sarabun', sans-serif" },
  { name: "Mitr", value: "'Mitr', sans-serif" },
  { name: "Chonburi", value: "'Chonburi', cursive" },
  { name: "IBM Plex Sans Thai", value: "'IBM Plex Sans Thai', sans-serif" },
  { name: "Noto Sans Thai", value: "'Noto Sans Thai', sans-serif" },
  { name: "Sriracha", value: "'Sriracha', cursive" },
  { name: "Krub", value: "'Krub', sans-serif" },
  { name: "Mali", value: "'Mali', cursive" },
  { name: "Taviraj", value: "'Taviraj', serif" },
  { name: "Pattaya", value: "'Pattaya', sans-serif" },
  { name: "Itim", value: "'Itim', cursive" },
  { name: "Bai Jamjuree", value: "'Bai Jamjuree', sans-serif" },
  { name: "Pridi", value: "'Pridi', serif" },
  { name: "Niramit", value: "'Niramit', sans-serif" },
  { name: "Chakra Petch", value: "'Chakra Petch', sans-serif" },
  { name: "Trirong", value: "'Trirong', serif" },
  { name: "Athiti", value: "'Athiti', sans-serif" },
  { name: "Kodchasan", value: "'Kodchasan', sans-serif" },
  { name: "Thasadith", value: "'Thasadith', sans-serif" },
  { name: "Srisakdi", value: "'Srisakdi', cursive" },
  { name: "Charm", value: "'Charm', cursive" },
  { name: "K2D", value: "'K2D', sans-serif" },
  { name: "Fahkwang", value: "'Fahkwang', sans-serif" },
  { name: "KoHo", value: "'KoHo', sans-serif" },
  { name: "Maitree", value: "'Maitree', serif" },
  { name: "Charmonman", value: "'Charmonman', sans-serif" },
  { name: "Anuphan", value: "'Anuphan', sans-serif" },
  { name: "Kancha", value: "'Kancha', sans-serif" },
];

export const englishFonts = [
  { name: "Inter", value: "Inter, sans-serif" },
  { name: "Anton", value: "'Anton', sans-serif" },
  { name: "Bebas Neue", value: "'Bebas Neue', sans-serif" },
  { name: "Montserrat", value: "Montserrat, sans-serif" },
  { name: "Space Grotesk", value: "Space Grotesk, sans-serif" },
  { name: "Roboto", value: "'Roboto', sans-serif" },
  { name: "Open Sans", value: "'Open Sans', sans-serif" },
  { name: "Lato", value: "'Lato', sans-serif" },
  { name: "Oswald", value: "'Oswald', sans-serif" },
  { name: "Raleway", value: "'Raleway', sans-serif" },
  { name: "Poppins", value: "'Poppins', sans-serif" },
  { name: "Nunito Sans", value: "'Nunito Sans', sans-serif" },
  { name: "Merriweather", value: "'Merriweather', serif" },
  { name: "Playfair Display", value: "'Playfair Display', serif" },
  { name: "Ubuntu", value: "'Ubuntu', sans-serif" },
  { name: "Arimo", value: "'Arimo', sans-serif" },
  { name: "Dosis", value: "'Dosis', sans-serif" },
  { name: "Exo 2", value: "'Exo 2', sans-serif" },
  { name: "Fjalla One", value: "'Fjalla One', sans-serif" },
  { name: "Josefin Sans", value: "'Josefin Sans', sans-serif" },
  { name: "Lobster", value: "'Lobster', cursive" },
  { name: "Pacifico", value: "'Pacifico', cursive" },
  { name: "Permanent Marker", value: "'Permanent Marker', cursive" },
  { name: "Archivo", value: "'Archivo', sans-serif" },
  { name: "Barlow", value: "'Barlow', sans-serif" },
  { name: "Caveat", value: "'Caveat', cursive" },
  { name: "Comfortaa", value: "'Comfortaa', cursive" },
  { name: "Dancing Script", value: "'Dancing Script', cursive" },
  { name: "Poiret One", value: "'Poiret One', cursive" },
  { name: "Titillium Web", value: "'Titillium Web', sans-serif" },
];

export const allFonts = [...thaiFonts, ...englishFonts];
